apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  postgres-user: dm9jYWJfY29yZS03MzI5ODc=
  postgres-pass: YTM5LnBvc3RncmVzcWwtcGFzcy5uMzE=
