apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres-url: postgres-service
  postgres-db: vocab-db
---
# This secret can be public because the db we use
# is only accessible within the cluster.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  postgres-user: dm9jYWJfY29yZS03MzI5ODc=
  postgres-pass: YTM5LnBvc3RncmVzcWwtcGFzcy5uMzE=
