---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vocab-core
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: vocab-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vocab-core
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vocab-core
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - name: vocab-core
          image: eu.gcr.io/peak-bebop-370821/vocab-core:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: postgres-user
                  name: postgres-secret
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: postgres-db
                  name: postgres-config
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-pass
                  name: postgres-secret
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vocab-core
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: vocab-core
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: vocab-core
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
