package bh.sp.vocab.core.model.vocab;

import java.util.List;

import bh.sp.vocab.core.model.vocab.item.VocabItemEntity;

public class VocabSetPreset {

  public static List<VocabItemEntity> ingang1() {
    return List.of(
        VocabItemEntity.of("with", "met"),
        VocabItemEntity.of("get to know", "kennismaken"),
        VocabItemEntity.of("who", "wie"),
        VocabItemEntity.of("are", "ben (zijn)"),
        VocabItemEntity.of("you", "jij"),
        VocabItemEntity.of("what", "wat"),
        VocabItemEntity.of("your (singular)", "jouw"),
        VocabItemEntity.of("name", "de naam"),
        VocabItemEntity.of("your (singular)", "je"),
        VocabItemEntity.of("first name", "de voornaam"),
        VocabItemEntity.of("surname", "de achternaam"),
        VocabItemEntity.of("from", "uit"),
        VocabItemEntity.of("which", "welk"),
        VocabItemEntity.of("country", "het land"),
        VocabItemEntity.of("England", "Engeland"),
        VocabItemEntity.of("neighbour", "de buurman"),
        VocabItemEntity.of("of", "van"),
        VocabItemEntity.of("how (what)", "hoe"),
        VocabItemEntity.of("what's your name?", "hoe heet jij?"),
        VocabItemEntity.of("where ... from", "waar ... vandaan"),
        VocabItemEntity.of("where", "waar"),
        VocabItemEntity.of("live", "woon (wonen)"),
        VocabItemEntity.of("now", "nu"),
        VocabItemEntity.of("address", "het adres"),
        VocabItemEntity.of("number", "het nummer"),
        VocabItemEntity.of("answer", "het antwoord"),
        VocabItemEntity.of("postal code", "de postcode"),
        VocabItemEntity.of("you", "u"),
        VocabItemEntity.of("Ms / Mrs", "mevrouw"),
        VocabItemEntity.of("have", "hebben (hebben)"),
        VocabItemEntity.of("teaches", "geeft les (lesgeven)"),
        VocabItemEntity.of("three", "drie"),
        VocabItemEntity.of("begin / start", "beginnen (beginnen)"),
        VocabItemEntity.of("my", "mijn"),
        VocabItemEntity.of("day", "dag"),
        VocabItemEntity.of("come", "kom (komen)"),
        VocabItemEntity.of("is called", "heet (heten)"),
        VocabItemEntity.of("China", "China"),
        VocabItemEntity.of("no", "nee"),
        VocabItemEntity.of("welcome (to)", "welkom (in)"),
        VocabItemEntity.of("good morning", "goedemorgen"),
        VocabItemEntity.of("everyone", "allemaal"),
        VocabItemEntity.of("course", "de cursus"),
        VocabItemEntity.of("the", "de"),
        VocabItemEntity.of("Dutch", "Nederlands"),
        VocabItemEntity.of("I", "ik"),
        VocabItemEntity.of("am", "ben (zijn)"),
        VocabItemEntity.of("and", "en"),
        VocabItemEntity.of("your (plural)", "jullie"),
        VocabItemEntity.of("teacher", "de docent"),
        VocabItemEntity.of("teachers", "docenten (docent)"),
        VocabItemEntity.of("you (plural)", "jullie"),
        VocabItemEntity.of("two", "twee"),
        VocabItemEntity.of("other", "andere"),
        VocabItemEntity.of("is", "is (zijn)"),
        VocabItemEntity.of("he", "hij"),
        VocabItemEntity.of("days", "dagen (de dag)"),
        VocabItemEntity.of("we", "we"),
        VocabItemEntity.of("live", "woont (wonen)"),
        VocabItemEntity.of("also", "ook"),
        VocabItemEntity.of("in", "in"),
        VocabItemEntity.of("call (say)", "zeg (zeggen)"),
        VocabItemEntity.of("but (just)", "maar"),
        VocabItemEntity.of("(for friendliness, usually not translated)", "hoor"),
        VocabItemEntity.of("yes", "ja"),
        VocabItemEntity.of("here", "hier"),
        VocabItemEntity.of("already", "al"),
        VocabItemEntity.of("twenty", "twintig"),
        VocabItemEntity.of("year", "het jaar"),
        VocabItemEntity.of("go on (continue)", "gaan verder (verdergaan)"),
        VocabItemEntity.of("lesson", "de les"),
        VocabItemEntity.of("has", "heeft (hebben)"),
        VocabItemEntity.of("everyone", "iedereen"),
        VocabItemEntity.of("book", "het boek"),
        VocabItemEntity.of("the", "het"),
        VocabItemEntity.of("text", "de tekst"),
        VocabItemEntity.of("one", "één"),
        VocabItemEntity.of("on", "op"),
        VocabItemEntity.of("page", "de bladzijde"),
        VocabItemEntity.of("eight", "acht"),
        VocabItemEntity.of("listen", "luisteren"),
        VocabItemEntity.of("to", "naar"),
        VocabItemEntity.of("read", "lezen"),
        VocabItemEntity.of("stop", "stoppen (stoppen)"),
        VocabItemEntity.of("for a moment", "even"),
        VocabItemEntity.of("it is", "het is"),
        VocabItemEntity.of("break", "de pauze"),
        VocabItemEntity.of("see you later", "tot straks"),
        VocabItemEntity.of("soon / later", "straks"));
  }

  public static List<VocabItemEntity> ingang2() {
    return List.of(
        VocabItemEntity.of("are sitting", "zitten (zitten)"),
        VocabItemEntity.of("canteen", "de kantine"),
        VocabItemEntity.of("this", "deze"),
        VocabItemEntity.of("seat / place", "de plaats"),
        VocabItemEntity.of("free", "vrij"),
        VocabItemEntity.of("yes", "ja hoor"),
        VocabItemEntity.of("okay / right", "zo"),
        VocabItemEntity.of("a(n)", "een"),
        VocabItemEntity.of("nice / delicious", "lekker"),
        VocabItemEntity.of("cup", "het kopje (de kop)"),
        VocabItemEntity.of("coffee", "de koffie"),
        VocabItemEntity.of("for a long time", "al lang"),
        VocabItemEntity.of("only", "pas"),
        VocabItemEntity.of("or", "of"),
        VocabItemEntity.of("what", "welke"),
        VocabItemEntity.of("actually / really", "eigenlijk"),
        VocabItemEntity.of("today", "vandaag"),
        VocabItemEntity.of("Thursday", "donderdag"),
        VocabItemEntity.of("August", "augustus"),
        VocabItemEntity.of("tomorrow", "morgen"),
        VocabItemEntity.of("it's my birthday", "ik ben jarig (jarig zijn)"),
        VocabItemEntity.of("how nice", "wat leuk"),
        VocabItemEntity.of("December", "december"),
        VocabItemEntity.of("so / therefore", "dus"),
        VocabItemEntity.of("winter", "de winter"),
        VocabItemEntity.of("get / receive", "krijg (krijgen)"),
        VocabItemEntity.of("any", "nog"),
        VocabItemEntity.of("visit / visitors", "het bezoek"),
        VocabItemEntity.of("brother", "de broer"),
        VocabItemEntity.of("younger", "jonger (jong)"),
        VocabItemEntity.of("but", "maar"),
        VocabItemEntity.of("certainly", "wel"),
        VocabItemEntity.of("taller", "langer (lang)"),
        VocabItemEntity.of("any more", "nog meer"),
        VocabItemEntity.of("brothers", "broers (broer)"),
        VocabItemEntity.of("sisters", "zussen (zus)"),
        VocabItemEntity.of("sister", "de zus"),
        VocabItemEntity.of("as well", "nog"),
        VocabItemEntity.of("look", "kijk (kijken)"),
        VocabItemEntity.of("photo", "de foto"),
        VocabItemEntity.of("oh", "goh"),
        VocabItemEntity.of("very", "heel"),
        VocabItemEntity.of("different / other", "ander"),
        VocabItemEntity.of("type", "het type"),
        VocabItemEntity.of("short", "kort"),
        VocabItemEntity.of("blonde", "blond"),
        VocabItemEntity.of("hair", "het haar"),
        VocabItemEntity.of("dark", "donker"),
        VocabItemEntity.of("parents", "de ouders"),
        VocabItemEntity.of("pay a visit", "komen op bezoek (op bezoek komen)"),
        VocabItemEntity.of("at the moment", "op dit moment"),
        VocabItemEntity.of("Indonesia", "Indonesië"),
        VocabItemEntity.of("are doing", "doen (doen)"),
        VocabItemEntity.of("there", "daar"),
        VocabItemEntity.of("on holiday", "op vakantie"),
        VocabItemEntity.of("holiday", "de vakantie"),
        VocabItemEntity.of("father", "de vader"),
        VocabItemEntity.of("for", "voor"),
        VocabItemEntity.of("his", "zijn"),
        VocabItemEntity.of("work", "het werk"),
        VocabItemEntity.of("season", "het seizoen"),
        VocabItemEntity.of("when", "wanneer"),
        VocabItemEntity.of("summer", "de zomer"),
        VocabItemEntity.of("know", "weet (weten)"),
        VocabItemEntity.of("not", "niet"),
        VocabItemEntity.of("tell", "vertel (vertellen)"),
        VocabItemEntity.of("(usually untranslated)", "eens"),
        VocabItemEntity.of("about", "over"),
        VocabItemEntity.of("family", "de familie"),
        VocabItemEntity.of("that", "dat"),
        VocabItemEntity.of("want / would like", "wil (willen)"),
        VocabItemEntity.of("late", "laat"),
        VocabItemEntity.of("11 o'clock", "11.00 uur"),
        VocabItemEntity.of("should / have to", "moeten (moeten)"),
        VocabItemEntity.of("again", "weer"),
        VocabItemEntity.of("to", "naar"));
  }
}
